/** Shared Indonesian labels for SHAPE categories. */
export const CATEGORY_LABELS: Record<string, string> = {
  // Spiritual Gifts
  TEACHING: "Mengajar",
  SERVING: "Melayani",
  LEADERSHIP: "Memimpin",
  GIVING: "Memberi",
  MERCY: "Mengasihani",
  FAITH: "Iman",
  WISDOM: "Hikmat",
  KNOWLEDGE: "Pengetahuan",
  EXHORTATION: "Menasihati",
  EVANGELISM: "Penginjilan",
  // Heart
  EDUCATION: "Pendidikan",
  SOCIAL_JUSTICE: "Keadilan Sosial",
  ARTS: "Seni/Kreativitas",
  HEALTH: "Kesehatan",
  FAMILY: "Keluarga",
  YOUTH: "Pemuda",
  MISSIONS: "Misi",
  COMMUNITY: "Komunitas",
  TECHNOLOGY: "Teknologi",
  ENVIRONMENT: "Lingkungan",
  // Abilities
  COMMUNICATION: "Komunikasi",
  ORGANIZATION: "Organisasi",
  ANALYTICAL: "Analitis",
  CREATIVE: "Kreatif",
  TECHNICAL: "Teknis",
  INTERPERSONAL: "Interpersonal",
  WRITING: "Menulis",
  MUSICAL: "Musik",
  LEADERSHIP_ABILITY: "Kepemimpinan",
  TEACHING_ABILITY: "Mengajar",
  // Experience
  SPIRITUAL_EXP: "Pengalaman Spiritual",
  PAINFUL_EXP: "Pengalaman Menyakitkan",
  EDUCATIONAL_EXP: "Pengalaman Pendidikan",
  WORK_EXP: "Pengalaman Kerja",
  MINISTRY_EXP: "Pengalaman Pelayanan",
  // Personality
  EXTROVERT: "Extrovert",
  INTROVERT: "Introvert",
  TASK: "Berorientasi Tugas",
  PEOPLE: "Berorientasi Relasi",
  STRUCTURED: "Terstruktur",
  FLEXIBLE: "Fleksibel",
  THINKER: "Pemikir",
  FEELER: "Perasa",
  LEADER: "Pemimpin",
  SUPPORTER: "Pendukung",
};
